# Generated by Django 3.1.2 on 2020-10-31 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quilljs.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loyalty_program', '0002_auto_20201025_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in_points', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', quilljs.fields.RichTextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOfferApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeem_time', models.DateTimeField(auto_now_add=True)),
                ('permitted', models.BooleanField(db_index=True, default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_offers', to='loyalty_program.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
